services:
  laravel:
    build: .
    volumes:
      - ./laravel-app:/var/www
    expose:
      - "9000"
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    volumes:
      - ./laravel-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80" # Ganti port sesuai kebutuhan
    depends_on:
      - laravel
    networks:
      - laravel_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
